# Generated by Django 3.0.3 on 2020-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('R', 'Residential'), ('C', 'Commercial'), ('In', 'Industrial'), ('If', 'Infrastructure'), ('E', 'Educational'), ('M', 'Medical')], max_length=25)),
                ('project_size', models.CharField(choices=[('L', 'Large'), ('M', 'Medium'), ('S', 'Small')], max_length=6)),
                ('cost', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=1000)),
                ('document_work', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=6)),
                ('reduced_rework', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=6)),
                ('fewer_claims', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=6)),
            ],
        ),
    ]
