# Generated by Django 3.0.3 on 2020-06-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='COST_PERCENT',
            field=models.FloatField(default=30.4),
        ),
        migrations.AddField(
            model_name='project',
            name='DURATION_PERCENT',
            field=models.FloatField(default=21.1),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='document_work',
            field=models.CharField(choices=[('', 'Choose..'), ('Very', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='fewer_claims',
            field=models.CharField(choices=[('', 'Choose..'), ('Very', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_size',
            field=models.CharField(choices=[('', 'Choose..'), ('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='reduced_rework',
            field=models.CharField(choices=[('', 'Choose..'), ('Very', 'Very High'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=6),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('', 'Choose..'), ('R', 'Residential'), ('C', 'Commercial'), ('In', 'Industrial'), ('If', 'Infrastructure'), ('E', 'Educational'), ('M', 'Medical')], max_length=25),
        ),
    ]
